- name: Setup KernelSU-Next
  run: |
    curl -LSs \
      https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh \
      -o ksu_setup.sh

    chmod +x ksu_setup.sh

    bash -x ksu_setup.sh v1.1.1

    echo "===== Check KernelSU ====="
    find . -maxdepth 3 -type d | grep -i kernelsu || true
    find . -maxdepth 3 -type d | grep -i ksu || true
